export const SEARCH_START = 'SEARCH_START';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILED = 'SEARCH_FAILED';
export const FETCH_BOOKS_START= 'FETCH_BOOKS_START';
export const FETCH_BOOKS_SUCCESS= 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_FAILED= 'FETCH_BOOKS_FAILED';
export const EDIT_BOOK_START = 'EDIT_BOOK_START';
export const EDIT_BOOK_SUCCESS = 'EDIT_BOOK_SUCCESS';
export const EDIT_BOOK_FAILED = 'EDIT_BOOK_FAILED';
export const ADD_BOOK_START = 'ADD_BOOK_START';
export const ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS';
export const ADD_BOOK_FAILED = 'ADD_BOOK_FAILED';
export const UPDATE_BOOK_START = 'UPDATE_BOOK_START';
export const UPDATE_BOOK_SUCCESS = 'UPDATE_BOOK_SUCCESS';
export const UPDATE_BOOK_FAILED = 'UPDATE_BOOK_FAILED';

